linters-settings:
  errcheck:
    ignore: fmt:.*,io/ioutil:^Read.*
    ignoretests: true

  goimports:
    local-prefixes: github.com/wdvxdr1123/ZeroBot

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  fast: false
  enable:
    - bodyclose
    #- deadcode
    #- depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    #- funlen
    #- goconst
    #- gocritic
    #- gocyclo
    - gofumpt
    - goimports
    - goprintffuncname
    #- gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - rowserrcheck
    - staticcheck
    #- structcheck
    #- stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    #- varcheck
    - whitespace
    - prealloc
    - predeclared
    - asciicheck
    #- revive
    - makezero
    #- interfacer


run:
  # default concurrency is a available CPU number.
  # concurrency: 4 # explicitly omit this value to fully utilize available resources.
  deadline: 5m
  issues-exit-code: 1
  tests: false

# output configuration options
output:
  formats:
   - format: "colored-line-number"
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

issues:
  # Fix found issues (if it's supported by the linter)
  fix: true
